### ISSUE TITLE
Verify SSL certificate or disable certificate verification

### ISSUE THREAD

**Issue by chrzyki** [clld/pycdstar#8]
`InsecureRequestWarnings` are annoying and they probably have a point. CDSTAR connections via HTTPS should either verify the certificate that is being used (`import certifi` ... `cert_reqs='CERT_REQUIRED'` & `ca_certs=certifi.where()`) or disable warnings (doesn't seem like the best idea -- `urllib3.disable_warnings()`).

**Comment by chrzyki** [comment]
Noticing this just now:

https://github.com/clld/pycdstar/blob/b445f159a5f31e804440800a8a4983101919d386/src/pycdstar/api.py#L58-L59

Is there any reason why the verification is set to false? With true, `requests` and `urllib3` are happy and make (as far as I can tell) perfectly validated SSL requests.

**Comment by xrotwang** [comment]
Good call. This could date back to a time, where the root cert used by GWDG wasn't always in the distros.
